### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by joejarlett** [lucianoratamero/sveltekit-capacitor-sample#2]
when running compiles, however when visiting http://localhost:3000/ in the browser I get the following error

```bash
C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\app\dist\plugin.cjs.js:20
        document.addEventListener('visibilitychange', this.handleVisibilityChange, false);
        ^

ReferenceError: document is not defined
    at new AppWeb (C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\app\dist\plugin.cjs.js:20:9)
    at C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\app\dist\plugin.cjs.js:8:78
    at async loadPluginImplementation (C:\Users\joe\Documents\web\dev\sveltekit-capacitor-sample\node_modules\@capacitor\core\dist\index.cjs.js:158:47)
error Command failed with exit code 1.
```

Any pointers?

**Comment by NelsonDJCR** [comment]
same problem 😞
